packages:
  - "apps/*"
  - "apps/core"
  - "!packages/*"
  - "!packages/medusa/*"
  - "!packages/medusa-telemetry"
  - "packages/admin-next/admin-shared"
  - "!packages/admin-next/admin-sdk"
  - "packages/admin-next/admin-vite-plugin"
  - "!packages/admin-next/dashboard"
  - "packages/design-system/ui-preset"
  - "packages/design-system/ui"
  - "packages/design-system/icons"
  - "packages/design-system/toolbox"
  - "packages/core/types"
  - "packages/core/utils"
  - "packages/core/workflows-sdk"
